const partidos = [
{ id:1, local:“MÉXICO”, visitante:“SUDÁFRICA”, r1:””, r2:”” },
{ id:2, local:“COREA del SUR”, visitante:“REP. CHECA”, r1:””, r2:”” },
{ id:3, local:“CANADÁ”, visitante:“BOSNIA Y HERZEG.”, r1:””, r2:”” },
{ id:4, local:“ESTADOS UNIDOS”, visitante:“PARAGUAY”, r1:””, r2:”” },
{ id:5, local:“CATAR”, visitante:“SUIZA”, r1:””, r2:”” },
{ id:6, local:“BRASIL”, visitante:“MARRUECOS”, r1:””, r2:”” },
{ id:7, local:“HAITÍ”, visitante:“ESCOCIA”, r1:””, r2:”” },
{ id:8, local:“AUSTRALIA”, visitante:“TURQUÍA”, r1:””, r2:”” },
{ id:9, local:“ALEMANIA”, visitante:“CURAZAO”, r1:””, r2:”” },
{ id:10, local:“PAÍSES BAJOS”, visitante:“JAPÓN”, r1:””, r2:”” },
{ id:11, local:“COSTA de MARFIL”, visitante:“ECUADOR”, r1:””, r2:”” },
{ id:12, local:“SUECIA”, visitante:“TÚNEZ”, r1:””, r2:”” },
{ id:13, local:“ESPAÑA”, visitante:“CABO VERDE”, r1:””, r2:”” },
{ id:14, local:“BÉLGICA”, visitante:“EGIPTO”, r1:””, r2:”” },
{ id:15, local:“ARABIA SAUDITA”, visitante:“URUGUAY”, r1:””, r2:”” },
{ id:16, local:“IRÁN”, visitante:“NUEVA ZELANDA”, r1:””, r2:”” },
{ id:17, local:“FRANCIA”, visitante:“SENEGAL”, r1:””, r2:”” },
{ id:18, local:“IRAK”, visitante:“NORUEGA”, r1:””, r2:”” },
{ id:19, local:“ARGENTINA”, visitante:“ARGELIA”, r1:””, r2:”” },
{ id:20, local:“AUSTRIA”, visitante:“JORDANIA”, r1:””, r2:”” },
{ id:21, local:“PORTUGAL”, visitante:“REP. del CONGO”, r1:””, r2:”” },
{ id:22, local:“INGLATERRA”, visitante:“CROACIA”, r1:””, r2:”” },
{ id:23, local:“GHANA”, visitante:“PANAMÁ”, r1:””, r2:”” },
{ id:24, local:“UZBEKISTÁN”, visitante:“COLOMBIA”, r1:””, r2:”” },
{ id:25, local:“REP. CHECA”, visitante:“SUDÁFRICA”, r1:””, r2:”” },
{ id:26, local:“SUIZA”, visitante:“BOSNIA y HERZEG.”, r1:””, r2:”” },
{ id:27, local:“CANADÁ”, visitante:“CATAR”, r1:””, r2:”” },
{ id:28, local:“MÉXICO”, visitante:“COREA del SUR”, r1:””, r2:”” },
{ id:29, local:“ESTADOS UNIDOS”, visitante:“AUSTRALIA”, r1:””, r2:”” },
{ id:30, local:“ESCOCIA”, visitante:“MARRUECOS”, r1:””, r2:”” },
{ id:31, local:“BRASIL”, visitante:“HAITÍ”, r1:””, r2:”” },
{ id:32, local:“TURQUÍA”, visitante:“PARAGUAY”, r1:””, r2:”” },
{ id:33, local:“PAÍSES BAJOS”, visitante:“SUECIA”, r1:””, r2:”” },
{ id:34, local:“ALEMANIA”, visitante:“COSTA de MARFIL”, r1:””, r2:”” },
{ id:35, local:“ECUADOR”, visitante:“CURAZAO”, r1:””, r2:”” },
{ id:36, local:“TÚNEZ”, visitante:“JAPÓN”, r1:””, r2:”” },
{ id:37, local:“ESPAÑA”, visitante:“ARABIA SAUDITA”, r1:””, r2:”” },
{ id:38, local:“BÉLGICA”, visitante:“IRÁN”, r1:””, r2:”” },
{ id:39, local:“URUGUAY”, visitante:“CABO VERDE”, r1:””, r2:”” },
{ id:40, local:“NUEVA ZELANDA”, visitante:“EGIPTO”, r1:””, r2:”” },
{ id:41, local:“ARGENTINA”, visitante:“AUSTRIA”, r1:””, r2:”” },
{ id:42, local:“FRANCIA”, visitante:“IRAK”, r1:””, r2:”” },
{ id:43, local:“NORUEGA”, visitante:“SENEGAL”, r1:””, r2:”” },
{ id:44, local:“JORDANIA”, visitante:“ARGELIA”, r1:””, r2:”” },
{ id:45, local:“PORTUGAL”, visitante:“UZBEKISTÁN”, r1:””, r2:”” },
{ id:46, local:“INGLATERRA”, visitante:“GHANA”, r1:””, r2:”” },
{ id:47, local:“PANAMÁ”, visitante:“CROACIA”, r1:””, r2:”” },
{ id:48, local:“COLOMBIA”, visitante:“REP. del CONGO”, r1:””, r2:”” },
{ id:49, local:“SUIZA”, visitante:“CANADÁ”, r1:””, r2:”” },
{ id:50, local:“BOSNIA y HERZEG.”, visitante:“CATAR”, r1:””, r2:”” },
{ id:51, local:“BRASIL”, visitante:“ESCOCIA”, r1:””, r2:”” },
{ id:52, local:“MARRUECOS”, visitante:“HAITÍ”, r1:””, r2:”” },
{ id:53, local:“REP. CHECA”, visitante:“MÉXICO”, r1:””, r2:”” },
{ id:54, local:“SUDÁFRICA”, visitante:“COREA del SUR”, r1:””, r2:”” },
{ id:55, local:“CURAZAO”, visitante:“COSTA de MARFIL”, r1:””, r2:”” },
{ id:56, local:“ECUADOR”, visitante:“ALEMANIA”, r1:””, r2:”” },
{ id:57, local:“JAPÓN”, visitante:“SUECIA”, r1:””, r2:”” },
{ id:58, local:“TÚNEZ”, visitante:“PAÍSES BAJOS”, r1:””, r2:”” },
{ id:59, local:“TURQUÍA”, visitante:“ESTADOS UNIDOS”, r1:””, r2:”” },
{ id:60, local:“PARAGUAY”, visitante:“AUSTRALIA”, r1:””, r2:”” },
{ id:61, local:“NORUEGA”, visitante:“FRANCIA”, r1:””, r2:”” },
{ id:62, local:“SENEGAL”, visitante:“IRAK”, r1:””, r2:”” },
{ id:63, local:“CABO VERDE”, visitante:“ARABIA SAUDITA”, r1:””, r2:”” },
{ id:64, local:“URUGUAY”, visitante:“ESPAÑA”, r1:””, r2:”” },
{ id:65, local:“EGIPTO”, visitante:“IRÁN”, r1:””, r2:”” },
{ id:66, local:“NUEVA ZELANDA”, visitante:“BÉLGICA”, r1:””, r2:”” },
{ id:67, local:“PANAMÁ”, visitante:“INGLATERRA”, r1:””, r2:”” },
{ id:68, local:“CROACIA”, visitante:“GHANA”, r1:””, r2:”” },
{ id:69, local:“COLOMBIA”, visitante:“PORTUGAL”, r1:””, r2:”” },
{ id:70, local:“REP. del CONGO”, visitante:“UZBEKISTÁN”, r1:””, r2:”” },
{ id:71, local:“ARGELIA”, visitante:“AUSTRIA”, r1:””, r2:”” },
{ id:72, local:“JORDANIA”, visitante:“ARGENTINA”, r1:””, r2:”” }
];
